image: vorpal/borealis-standalone:squashed

pipelines:
  default:
    - step:
        script:
          - echo "\n[subrepos]\ngit:allowed = true\n" >> ~/.hgrc
          - hg update
          - mkdir build
          - cd build
          - cmake ..
          - make
          - make check
