/*
 * Type/Bool.h
 * This file is generated from the following haskell datatype representation:
 * 
 * data Type = 
    Integer { bitsize :: UInt, signedness :: LLVMSignedness } |
    Bool |
    Float |
    UnknownType |
    Pointer { pointed :: Type, memspace :: Size } |
    Array { element :: Type, size :: Maybe Size } |
    Record { name :: String, body :: RecordBodyRef } |
    TypeError { message :: String } |
    Function { retty :: Type, args :: [Type] }
      deriving (Show, Eq, Data, Typeable)

 * 
 * stored in Type/Type.datatype
 * using the template file Type/derived.h.hst
 * 
 * DO NOT EDIT THIS FILE DIRECTLY
 */

#ifndef BOOL_H
#define BOOL_H

#include "Type/Type.h"
#include "Type/RecordBody.h" // including this is generally fucked up



namespace borealis {

class TypeFactory;

namespace type {

/** protobuf -> Type/Bool.proto
import "Type/Type.proto";
import "Type/RecordBodyRef.proto";



package borealis.type.proto;

message Bool {
    extend borealis.proto.Type {
        optional Bool ext = 2;
    }

}

**/
class Bool : public Type {

    typedef Bool Self;
    typedef Type Base;

    Bool(): Type(class_tag(*this)) {}

public:
    friend class ::borealis::TypeFactory;
    
    static bool classof(const Self*) { return true; }
    static bool classof(const Base* b) { return b->getClassTag() == class_tag<Self>(); }

};

} // namespace type
} // namespace borealis

#endif // BOOL_H
