/*
 * Type/Float.h
 * This file is generated from the following haskell datatype representation:
 * 
 * data Type = 
    Integer { bitsize :: UInt, signedness :: LLVMSignedness } |
    Bool |
    Float |
    UnknownType |
    Pointer { pointed :: Type } |
    Array { element :: Type, size :: Maybe Size } |
    Record { name :: String, body :: RecordBodyRef } |
    TypeError { message :: String } |
    Function { retty :: Type, args :: [Type] }
      deriving (Show, Eq, Data, Typeable)
 * 
 * stored in Type/Type.datatype
 * using the template file Type/derived.h.hst
 * 
 * DO NOT EDIT THIS FILE DIRECTLY
 */

#ifndef FLOAT_H
#define FLOAT_H

#include "Type/Type.h"
#include "Type/RecordBody.h" // including this is generally fucked up



namespace borealis {

class TypeFactory;

namespace type {

/** protobuf -> Type/Float.proto
import "Type/Type.proto";
import "Type/RecordBodyRef.proto";



package borealis.type.proto;

message Float {
    extend borealis.proto.Type {
        optional Float ext = 3;
    }

}

**/
class Float : public Type {

    typedef Float Self;
    typedef Type Base;

    Float(): Type(class_tag(*this)) {}

public:
    friend class ::borealis::TypeFactory;
    
    static bool classof(const Self*) { return true; }
    static bool classof(const Base* b) { return b->getClassTag() == class_tag<Self>(); }

};

} // namespace type
} // namespace borealis

#endif // FLOAT_H
