/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux lanthanum.local 4.5.1-1-ARCH x86_64"
#define LGL_COMPILED "Wed Jun 29 17:48:04 MSK 2016"
#define LGL_RELEASED "Sun Nov 29 18:40:12 CET 2015"
#define LGL_VERSION "bal"
#define LGL_ID "2293bef0a4bd680210f6f5a453efa8b0a26f53ee"
